### ISSUE TITLE
PKMN SuMo plg

### ISSUE THREAD

**Issue by JourneyOver** [adrifcastr/NTRDB-Plugin-Host#1]
Dunno exactly where you are pulling your pkmn sumo plugins from unless they are ones you created yourself, but if your pulling them from this thread http://gbatemp.net/threads/release-pok%C3%A9mon-sumocheatmenu-supports-o3ds.455365/ then there should be 2 versions for N3DS and O3DS. 1 for sun and 1 for moon, so in total you should have 4 plugins in total for SuMo.

**Comment by adrifcastr** [comment]
you are aware that there is no difference between the plg files for sun and moon?  #closed
